Repository redhat-cne/hw-event-proxy, pull requests merged in 2022-04, with the labels that each got.

#74 Add setup.cfg to message-parser
  message-parser/setup.cfg
Labels: approved, lgtm, ok-to-test

#72 Update sdk-go modules
  hw-event-proxy/go.mod
  hw-event-proxy/go.sum
  hw-event-proxy/vendor/github.com/redhat-cne/sdk-go/pkg/event/event_ce.go
  hw-event-proxy/vendor/github.com/redhat-cne/sdk-go/v1/event/event.go
  hw-event-proxy/vendor/modules.txt
Labels: approved, lgtm

#75 Update message-parser requirements files for cachito
  message-parser-cachito/build_requirements.in
  message-parser-cachito/build_requirements.txt
  message-parser-cachito/requirements.in
  message-parser-cachito/requirements.txt
  message-parser-cachito/setup.cfg
Labels: lgtm, ok-to-test

#76 Fix env/ entry in .gitignore
  .gitignore
  hw-event-proxy/vendor/google.golang.org/grpc/internal/xds/env/env.go
Labels: approved, lgtm, ok-to-test

#77 Fix flit_core cachito build failure
  message-parser-cachito/build_requirements.in
  message-parser-cachito/build_requirements.txt
Labels: ok-to-test
