Repository redhat-cne/hw-event-proxy, pull requests merged in 2022-06, with the labels that each got.

#83 Add Dockerfile.art build file
  Dockerfile.art
  message-parser/requirements.txt
Labels: lgtm, ok-to-test

#84 Fix typo in Dockerfile.art
  Dockerfile.art
Labels: approved, lgtm, ok-to-test

#85 update docker file to reconcile with art
  Dockerfile.art
Labels: approved, lgtm, ok-to-test

#87 Remove python3.6 alternative in image
  Dockerfile.art
Labels: approved, lgtm
