Repository redhat-cne/hw-event-proxy, pull requests merged in 2023-02, with the labels that each got.

#102 BUG OCPBUGS-7441: Match the O-RAN specification for the ocloudNotifications URI
  README.md
  hw-event-proxy/cmd/main.go
  manifests/consumer/deployment.yaml
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, jira/severity-moderate, jira/valid-reference, jira/valid-bug

#101 configure persistent storage for event producer
  Makefile
  docs/development.md
  manifests/layers/proxy-pvc/kustomization.yaml
  manifests/layers/proxy-pvc/pvc.yaml
  manifests/layers/proxy-pvc/update-pvc.yaml
  manifests/pv/kustomization.yaml
  manifests/pv/lv.yaml
  manifests/pv/pv.yaml
  manifests/pv/storage-class.yaml
Labels: approved, lgtm

#103 Update sdk-go and fix Redfish Oem field
  e2e-tests/data/IDRAC.2.8.TMP0110
  e2e-tests/data/README.md
  hw-event-proxy/go.mod
  hw-event-proxy/go.sum
  hw-event-proxy/vendor/github.com/redhat-cne/sdk-go/pkg/channel/doc.go
  hw-event-proxy/vendor/github.com/redhat-cne/sdk-go/pkg/channel/pipeline.go
  hw-event-proxy/vendor/github.com/redhat-cne/sdk-go/pkg/channel/types.go
  hw-event-proxy/vendor/github.com/redhat-cne/sdk-go/pkg/event/event.go
  hw-event-proxy/vendor/github.com/redhat-cne/sdk-go/pkg/event/event_ce.go
  hw-event-proxy/vendor/github.com/redhat-cne/sdk-go/pkg/event/event_data.go
  hw-event-proxy/vendor/github.com/redhat-cne/sdk-go/pkg/event/event_writer.go
  hw-event-proxy/vendor/github.com/redhat-cne/sdk-go/pkg/event/redfish/event_marshal.go
  hw-event-proxy/vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub.go
  hw-event-proxy/vendor/github.com/redhat-cne/sdk-go/pkg/types/value.go
  hw-event-proxy/vendor/github.com/redhat-cne/sdk-go/pkg/util/wait/wait.go
  hw-event-proxy/vendor/modules.txt
Labels: approved, lgtm

#106 Update e2e test with redhat-cne images
  Makefile
  e2e-tests/data/IDRAC.2.8.TMP0110.json
  manifests/consumer/kustomization.yaml
  manifests/proxy/kustomization.yaml
Labels: approved, lgtm

#105 Added a comment to manually propagate Dockerfile changes to the midstream repo
  Dockerfile
Labels: approved, lgtm

#107 [release-4.12] Bug OCPBUGS-7486: Match the O-RAN spec for ocloudNotifications URI
  README.md
  hw-event-proxy/cmd/main.go
  manifests/consumer/deployment.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-moderate, jira/valid-reference, jira/valid-bug

#108 [release-4.11] Bug OCPBUGS-8039: Match the O-RAN spec for ocloudNotifications URI
  README.md
  hw-event-proxy/cmd/main.go
  manifests/base/consumer.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-moderate, jira/valid-reference, jira/valid-bug
